name: Reviewdog

on:
  push:
  pull_request:

jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
